#!/bin/bash


if [[ "$EUID" -ne 0 ]]; then
	echo "Error: run script with sudo"
	exit 1
fi


highestuserid=$(awk --field-separator ":" '{print $3}' /etc/passwd | sort -nr | grep -E '\b[0-9]{4}\b' | head -n 1)

newUid=$(($highestuserid + 1))
newGuid=$newUid
name=""
specifiedshell="/bin/bash"



while getopts "u:g:s:" opt; do
	case "${opt}" in
	u)
		name=${OPTARG}
		;;
	g)
		groups=( ${OPTARG} )
		;;

	s)
		specifiedshell=${OPTARG}
		;;
		
	:)
		echo "Error:this flag requires an argument"
		exit 1
		;;
	?)
		echo "Error: this option does not exist
		-u <username> (example: -u arch)
		-g <"groups"> (example: -g 'wheel adm group3')
		-s shell (example: -s /bin/bash) 
		"
		exit 1
		;;
	esac
done

if [[ $(cat /etc/passwd | grep $name) ]]; then
	echo "Error: This user already exists please provide a unique user"
	exit 1
fi

if [[ $# -eq 0 ]]; then
	echo "Error: no options or arguments were passed
        -u <username> (example: -u arch)
        -g <"groups"> (example: -g 'wheel adm group3')
        -s shell (example: -s /bin/bash)"
	exit 1
fi



if [[ ! $(cat /etc/shells | grep $specifiedshell) ]]; then
	echo "this shell cannot be set it is not in the /etc/shells file to set your shell to $specifiedshell download it first"
	exit 1
fi


for i in ${groups[@]}; do
	if [[ ! $(cat /etc/group | grep $i) ]]; then
		echo "Error: one of these groups dont exist run the script again with existing groups"
	exit 1
	fi
done



if [[ -n $name && -n $specifiedshell ]]; then
	
	echo "$name:x:$newUid:$newGuid:$name:/home/$name:$specifiedshell" >> /etc/passwd
	echo "$name:x:$newGuid:" >> /etc/group
	mkdir -p /home/$name
	cp -r /etc/skel/. /home/$name
	chown $name:$name /home/$name
	echo "$name:!*:::::::" >> /etc/shadow

	for i in ${groups[@]}; do
		groupline=$(cat /etc/group | grep -w "$i:x")
		command=$(cat /etc/group | grep -w "$i:x" | awk -F'[ :]' '{print $4}')
		if [[ $command ]]; then
			newline=$(sed "s/$/,${name}/" <<< $groupline)
			sed -i "s/${groupline}/${newline}/g" /etc/group
		else
			nofirstuser=$(sed "s/$/${name}/" <<< $groupline)
			sed -i "s/${groupline}/${nofirstuser}/g" /etc/group
		fi
	done	
passwd $name
echo "successful: User $name is created"
else
	echo "Error: provide a username and specifiedshell"
fi








